### ISSUE TITLE
5) Hello World Tutorial

### ISSUE THREAD

**Issue by carrera1** [jhu-en-525-615-fa21/lab1-carrera1#3]
# TODO
* [ ] Complete [Hello World Tutorial](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#hello-world-tutorial)

**Comment by carrera1** [comment]
# Problem

Went to Run -> Debug Configurations... -> Debugger Tab

Using following options:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/26331265/131937464-88f4a7c2-a963-48e8-8b0a-5cd579b11c83.png">

Upon pressing "debug" button, receive the following error

<img width="399" alt="image" src="https://user-images.githubusercontent.com/26331265/131937203-1884d528-353e-4c58-9285-2521da61f3df.png">

# Likely Cause

macOS does not come with `gdb` nor `gcc`. In fact, the default `gcc` on macOS is really just `llvm`/`clang` as shown below

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/26331265/131937743-d0eef6cd-5420-4bf7-8f8e-b734bcb06472.png">

# Next Steps

* [ ] Determine if `lldb` can be used with STM32CubeIDE/Eclipse. If so, test out w/ Hello_World_Tutorial and document steps
  * The [CDT User FAQ](https://wiki.eclipse.org/CDT/User/FAQ) seems to have relevant info
  * [8.24 How do I use GDB on recent versions of macOS?](https://wiki.eclipse.org/CDT/User/FAQ#How_do_I_use_GDB_on_recent_versions_of_macOS.3F)
  * [8.25 How do I get the LLDB debugger](https://wiki.eclipse.org/CDT/User/FAQ#How_do_I_get_the_LLDB_debugger.3F)
  * [8.26 How do I install the LLDB debugger integration](https://wiki.eclipse.org/CDT/User/FAQ#How_do_I_install_the_LLDB_debugger_integration.3F)
  * [8.27 How do I debug with LLDB](https://wiki.eclipse.org/CDT/User/FAQ#How_do_I_debug_with_LLDB.3F)
  * [8.28 What are the limitations of using the LLDB debugger in Eclipse](https://wiki.eclipse.org/CDT/User/FAQ#What_are_the_limitations_of_using_the_LLDB_debugger_in_Eclipse.3F)
* [ ] Alternatively... just install `gdb` from source via macports or home-brew, and supply the path to `gdb` in Eclipse
  *  The [CDT User FAQ](https://wiki.eclipse.org/CDT/User/FAQ) seems to imply in previously linked "[8.24 How do I use GDB on recent versions of macOS?](https://wiki.eclipse.org/CDT/User/FAQ#How_do_I_use_GDB_on_recent_versions_of_macOS.3F)", there might be... issues with `gdb` in macOS due to security (code-signing?) reasons

> In recent versions of macOS and Xcode, Apple's GDB is not provided by default. However, it is possible to use the "normal" GDB provided by the Free Software Foundation. For easy installation, you can use package systems such as Brew and MacPorts. Once installed, when you start debugging with GDB you will see an error message such as:
>
> Unable to find Mach task port for process-id 28885: (os/kern) failure (0x5).
 (please check gdb is codesigned - see taskgated(8))
In this case, you need to code sign GDB by following the instructions available at http://sourceware.org/gdb/wiki/BuildingOnDarwin
>
> Note that if GDB is installed with MacPorts, the executable will be named 'ggdb'. You can adjust the preferences in Eclipse to always use this command by going in Preferences > C/C++ > Debug > GDB then change the command to ggdb instead of gdb.
>
> For macOS Sierra (10.12), there seems to be additional problems with GDB that might make it unusable, see the [GDB bug report](https://sourceware.org/bugzilla/show_bug.cgi?id=20266).

NOTE: Appears to be resolved in the reference bug report

**Comment by carrera1** [comment]
GDB appears to be unusable in macOS since High Sierra (currently on Big Sur 11.5.2)

LLDB doesn't play nice with Eclipse unless building everything from scratch.

In the interest of time, will just spin up a VM for this lab (and course if necessary)

**Comment by carrera1** [comment]
#8 resolves this issue.
