### ISSUE TITLE
6) Programming Examples Tutorial

### ISSUE THREAD

**Issue by carrera1** [jhu-en-525-615-fa21/lab1-carrera1#4]
# TODO
* [x] [Programming Examples Tutorial](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#programming-examples-tutorial)
* [x]  [Project Setup](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#project-setup)
* [x]  [example_v0](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#example_v0)
* [x]  [example_v1](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#example_v1)
* [x]  [example_v2](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#example_v2)
* [x]  [example_v3](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#example_v3)
* [x]  [example_v4](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#example_v4)
* [x]  [Example Notes](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#example-notes)

## NOTE
Depending on Complexity, may kick off new issues per task
