### ISSUE TITLE
7) Programming Lab Exercises

### ISSUE THREAD

**Issue by carrera1** [jhu-en-525-615-fa21/lab1-carrera1#5]
# TODO
* [ ] [Programming Lab Exercises](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#programming-lab-exercises)
* [ ] [Project Setup](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#project-setup-1)
* [ ] [Exercise 1](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#exercise-1)
* [ ] [Exercise 2](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#exercise-2)
* [ ] [Exercise 3](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#exercise-3)
* [ ] [Exercise 4](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#exercise-4)
* [ ] [Exercise 5](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#exercise-5)
* [ ] [Exercise 6](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#exercise-6)
* [ ] [Exercise 7](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#exercise-7)
* [ ] [Exercise 8](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#exercise-8)
* [ ] [Exercise 9](https://github.com/jhu-en-525-615-fa21/lab1-carrera1/blob/master/docs/lab1.adoc#exercise-9)

## NOTE
Depending on Complexity, may kick off new issues per task
